version: '3.8'
services:
  pg-test:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    volumes:
#      - db:/var/lib/postgresql/data
