create table tasks (
    task_id     int     primary key generated always as identity,
    assign_to   int                         null,
    status_id   int                     not null,
	description text                    not null
);
--drop table tasks;

create table task_statuses (
    status_id   int     primary key generated by default as identity,
    name        text                    not null,
    available   boolean not null
);
--drop table task_statuses;

insert into task_statuses(status_id, name, available) values
(1, 'TODO', true),
(3, 'DONE', false);
--select * from task_statuses;
--delete from task_statuses;

insert into tasks(status_id, description) values
(1, 'Написать код'),
(1, 'Написать тесты'),
(2, 'Запустить тесты'),
(1, 'Установить на сервер');
--select * from tasks;
--delete from tasks;